### ISSUE TITLE
Failed to execute script artemis_firmware_uploader_gui on Win7 & 10

### ISSUE THREAD

**Issue by MPH01** [sparkfun/Artemis-Firmware-Upload-GUI#11]
artemis_firmware_uploader_gui.exe produces error "Failed to execute script artemis_firmware_uploader_gui" on Windows 7 & 10. I've also tried "Run as Administrator" and disabling my anti-virus.

If you need more information let me know.

**Comment by PaulZC** [comment]
Hi @MPH01 ,

I finally found time to publish the new version of the GUI. The executables are now compiled using GitHub Actions and are automatically attached to each new release.

Can you please give v3.0.0 a try and let me know what you find?

https://github.com/sparkfun/Artemis-Firmware-Upload-GUI/releases

Sincere thanks,
Paul

**Comment by PaulZC** [comment]
Closing this... Please reopen if you need more help.

Best wishes,
Paul
