### ISSUE TITLE
Unable to upload in Linux, but able to in Windows

### ISSUE THREAD

**Issue by miquelmassot** [sparkfun/Artemis-Firmware-Upload-GUI#12]
Hi all,

thanks for this amazing tool. Just wanted to mention that when I was trying to use it in Ubuntu 22.04 I faced issues where the board would not reply to any commands (I am using a SparkX Artemis Global Tracker), failing all steps. I rebooted to windows 11 on the same machine and used your windows tool and it did work straight away.

Happy to debug this if you let me know what to do.

**Comment by PaulZC** [comment]
Hi Miquel (@miquelmassot ),

My colleague has been experimenting with new ways to compile the executables - for multiple platforms. If you have time, maybe you could try the linux.gz from here:

https://github.com/kirk-sfe/Artemis-Firmware-Upload-GUI/releases/tag/v0.6.0

Many thanks,
Paul

**Comment by PaulZC** [comment]
Hi Miquel (@miquelmassot ),

I finally found time to publish the new version of the GUI. The executables are now compiled using GitHub Actions and are automatically attached to each new release.

Can you please give v3.0.0 a try and let me know what you find?

https://github.com/sparkfun/Artemis-Firmware-Upload-GUI/releases

Sincere thanks,
Paul

**Comment by miquelmassot** [comment]
Hi @PaulZC, thanks for the update! I will give it a go in the next two weeks.

**Comment by PaulZC** [comment]
Closing this... Please reopen if you need more help.

Best wishes,
Paul
