### ISSUE TITLE
Software does not run on current Macs [February 2023]; Solved

### ISSUE THREAD

**Issue by jliphard** [sparkfun/Artemis-Firmware-Upload-GUI#13]
On both Mac ARM silicon and Mac Intel, the software starts, consumes all available memory, and then crashes.

**Comment by jliphard** [comment]
Troubleshooting Notes

Tried: 

`% pyinstaller --windowed -n ArtemisFirmwareUploader --noconsole --distpath=. --icon=artemis_firmware_uploader_gui.ico --add-data="artemis_svl.bin:." --add-data="Artemis-Logo-Rounded.png:." artemis_firmware_uploader_gui.py`

This gives `ModuleNotFoundError: No module named 'PIL'`. 
Thus, `% pip3 install Pillow`. 

This yields "INFO: Building BUNDLE BUNDLE-00.toc completed successfully." and a `.app` that when double clicked crashes immediately.

Then tried to simply run the `.py`. 

This gives `ModuleNotFoundError: No module named 'PyQt5'`. 
Thus, `% pip3 install pyqt5`.

This gives `ModuleNotFoundError: No module named 'serial'.`
Thus, `% pip3 install serial`.

SUCCESS! Gui boots and runs. 

`% python3 artemis_firmware_uploader_gui.py`.

**Comment by PaulZC** [comment]
Hi Jan (@jliphard ),

Thanks for the update - glad you were able to find a solution!

We have been experimenting with new ways to automatically compile the executables - using [GitHub Actions](https://github.com/kirk-sfe/Artemis-Firmware-Upload-GUI). I'll leave this issue open until we make the new version public - and will make sure your fix is in there.

Many thanks,
Paul

**Comment by PaulZC** [comment]
Closing this...

Please see the [releases](https://github.com/sparkfun/Artemis-Firmware-Upload-GUI/releases) page for the latest executables - including MacOS.
