### ISSUE TITLE
Where is python requirements.txt file?

### ISSUE THREAD

**Issue by AlienSarlak** [sparkfun/Artemis-Firmware-Upload-GUI#16]
Hi,

I want to use this tool, but I can't find the requirements.txt file, which is the standard way to list Python packages. Is it a good idea to consider using one? It makes using the tools much easier and user-friendly.

**Comment by AlienSarlak** [comment]
[requirements.txt](https://github.com/user-attachments/files/15751208/requirements.txt)
might be helpful

**Comment by PaulZC** [comment]
Hi Ali (@AlienSarlak ),

We use GitHub Actions (Workflows) to build the executables: [.github/workflows](https://github.com/sparkfun/Artemis-Firmware-Upload-GUI/tree/master/.github/workflows). The requirements are in there - and vary slightly from platform to platform: 

https://github.com/sparkfun/Artemis-Firmware-Upload-GUI/blob/53836aa7a6e96a8e3146eb77a4a48a9760d113f7/.github/workflows/build-windows.yml#L36

Please feel free to fork this repo and add your own requirements file for your chosen platform.

Best wishes,
Paul

**Comment by AlienSarlak** [comment]
Thanks for the info
