### ISSUE TITLE
Firmware Does Not Run After Upload

### ISSUE THREAD

**Issue by khosrowj** [sparkfun/Artemis-Firmware-Upload-GUI#3]
First, I would like to thank you for this very useful application. 
The first time I used this application, I was able to  upload the bootloader and the provided blink.bin image into my Artemis RedBoard and both worked as expected.

Next, I uploaded some Arduino examples provided by the Arduino IDE and went back to your application to upload bootloader and the blink.bin image again.

Both operation completed successfully with no error but the Blink application does not start to run after the upload its image anymore.

If I revert back to use the Arduino IDE and their e4xamples, the examples gets uploaded and run fine.

I do not know why uploading your blink.bin image worked the first time but not in subsequent uploads.,

**Comment by nseidle** [comment]
Thanks! Glad you find it helpful.

What board are you loading blink onto? I suspect you are using a board that has the status LED somewhere different than pin 19. Please download this [Blink.bin](https://github.com/sparkfun/Artemis-Firmware-Upload-GUI/blob/PaulZC_Integrated_Uploader/Blink.bin) as it will toggle a variety of pins that should support your board.

**Comment by khosrowj** [comment]
I am using the Artemis RedBoard (https://www.sparkfun.com/products/15444).

I confirm that I can successfully upload and run the new Blink.bin image that you have provided above now.

Thank you so much for your help.

**Comment by nseidle** [comment]
Happy to help! Keep an eye out for v2. It will include the new blink binary and work on OSX/Linux.

**Comment by khosrowj** [comment]
Great, I will be looking forward to that!
