### ISSUE TITLE
Uploader fails in Linux Mint 19.1; PyQt5 not found

### ISSUE THREAD

**Issue by n8ur** [sparkfun/Artemis-Firmware-Upload-GUI#8]
I know the executable was compiled under Ubuntu, but since Linux Mint is a derivative I thought it should work...

Attempting to run the program terminates with an error:
ModuleNotFoundError: No module named 'PyQt5'

I've checked and both python-pyqt5 and python3-pyqt5 are installed.

UPDATE: After realizing I needed to launch the .py using "python3 Artemis..." rather than assuming there was a shebang, I found the problem is that pyqt5.serialport was not installed.  After installing that, I can run the .py script.  But running the provided executable still fails with the missing PyQt5 error.

**Comment by tykling** [comment]
I am experiencing this same issue on Debian 10. Would be nice if the linux executable would come bundled with what it needs, or to have a normal setup.py with depends or a requirements.txt to make it work.

**Comment by jerabaul29** [comment]
Same on Ubuntu 20.04. I had to fiddle around with a bit of apt install and pip3 in order to get the python3 script https://github.com/sparkfun/Artemis-Firmware-Upload-GUI/blob/master/tools/artemis_firmware_uploader_gui.py . After a bit of fixing dependencies it works well. I cannot get the executable to work.

**Comment by timur-tabi** [comment]
This bug has been around for almost a year, and still no fix?  I'm also using Ubuntu 20 and have the same problem.

**Comment by timur-tabi** [comment]
I managed to get it working by installing a couple python3 modules:

    sudo apt-get install python3-pyqt5.qtserialport python3-serial

However, only the python script in "tools" works.  The GUI says that module PyQt5 cannot be found.

**Comment by Chlorophytus** [comment]
On openSUSE:

```
sudo zypper install python38-qt5
sudo zypper install python38-pyserial
```

**Comment by jerabaul29** [comment]
Any update? Still not working on Ubuntu...

**Comment by PaulZC** [comment]
Hi @n8ur / All,

I finally found time to publish the new version of the GUI. The executables are now compiled using GitHub Actions and are automatically attached to each new release.

Can you please give v3.0.0 a try and let me know what you find?

https://github.com/sparkfun/Artemis-Firmware-Upload-GUI/releases

Sincere thanks,
Paul

**Comment by PaulZC** [comment]
Closing this... Please reopen if you need more help.

Best wishes,
Paul
